<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.3.1.min.js'))
        ?>
		
		
		
		
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('application', ['action' => 'CV']); ?>">
                        <img src="<?= $this->basePath('img/scg-icon.png') ?>" height="28" alt="Zend Framework <?= \Application\Module::VERSION ?>"/>&nbsp; Test Application
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
							<ul class="navbar-nav mr-auto">
							  <li class="nav-item">
								<a class="nav-link" href="<?= $this->url('application', ['action' => 'CV']); ?>">Profile CV </a>
							  </li>
							  <li class="nav-item">
								<a class="nav-link" href="<?= $this->url('application', ['action' => 'XYZ']); ?>">XYZ</a>
							  </li>
							  <li class="nav-item">
								<a class="nav-link"  href="<?= $this->url('application', ['action' => 'BC']); ?>">Finding BC</a>
							  </li>
							  
							</ul>
				  </div>
                
                    
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>Created By 
				Mr. Bundhit Ngamsanguan</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
